<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>DotNetRastreioSearch</PackageId>
    <Authors>João Paulo de Castro Lima</Authors>
    <Company>joao2391</Company>
    <Product>DotNetRastreioSearch</Product>
    <Description>It is a library that helps you to track your objects in Correios</Description>
    <PackageProjectUrl>https://github.com/joao2391/DotNetRastreioSearh</PackageProjectUrl>
    <RepositoryUrl>https://github.com/joao2391/DotNetRastreioSearh</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>Git</RepositoryType>
    <PackageTags>webcrawling; webscrap; cep; correios; dotnetcore; dotnetstandard;</PackageTags>
    <PackageReleaseNotes>Beta Version</PackageReleaseNotes>
	<Version>1.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.23" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.8" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Microsoft.Playwright" Version="1.46.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Runtime.Caching" Version="8.0.0" />
  </ItemGroup>

</Project>
